name: Github Actions Demonstration
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:g
        - uses: actions/checkout@v2
        - run: echo "The Job was automatically triggered by a push event again."
        - run: python master.py
        